### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jamesedmonston** [jamesedmonston/graphql-authentication#1]
Documentation needs fleshing out with richer examples and walkthroughs (maybe a screen recording running through query/mutation examples).

**Comment by jamesedmonston** [comment]
New documentation now available: https://graphql-authentication.jamesedmonston.co.uk

**Comment by magicspon** [comment]
Do you have an example of using this to create/edit entries? 
I've successfully used the login/register endpoints.  Now i'm trying to add some content.
