### ISSUE TITLE
Activated account when registered with social 

### ISSUE THREAD

**Issue by cvitko** [jamesedmonston/graphql-authentication#100]
Is it possible to send email with email address verification when user normally registers,
but when user uses social account to register, account will be automatically activated without sending email address verification.
We know that e-mail address exists when user use social account.

Is this somehow possible? Thanks for help.

**Comment by jamesedmonston** [comment]
@magicspon hey, sorry to ping you for this but this kind of relates to your issue (https://github.com/jamesedmonston/graphql-authentication/issues/72). Do you have any thoughts about the proposed change?

Would a toggle to enable/disable the activation email for social signups be okay?

Currently, _any_ new accounts follow Craft's activation process.

**Comment by magicspon** [comment]
a toggle would be great.
i've got another project where the email verification for social logins would be best disabled, but enabled for regular email sign ups.

**Comment by jamesedmonston** [comment]
Working on this now. You'll see a new toggle on the social settings screen (defaults to `false`).

<img width="1792" alt="Screenshot 2022-09-10 at 14 57 46" src="https://user-images.githubusercontent.com/4851924/189486720-73710f62-673c-4488-bf77-4083184a12a6.png">

**Comment by jamesedmonston** [comment]
Released in `2.1.0`!
