### ISSUE TITLE
updateViewer mutation not working in 2.0

### ISSUE THREAD

**Issue by cvitko** [jamesedmonston/graphql-authentication#101]
Craft 4 + graphql-authentication 2.0

It runs without error. But user details are not updated.
I tried in my app and on https://graphiql-online.com. It is the same.

I am pretty sure it worked on craft 3 and previous version of plugin.

Other mutations and queries are working fine.

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/4570510/189294864-0dbed36d-9128-40a3-8f46-aa218dae2c00.png">

**Comment by jamesedmonston** [comment]
@cvitko Craft 4 merged the first/last name fields into `fullName`. I'm updating the mutation to user that field instead.

**Comment by jamesedmonston** [comment]
Released in `2.1.0`!
