### ISSUE TITLE
deleteAccount mutation not working

### ISSUE THREAD

**Issue by cvitko** [jamesedmonston/graphql-authentication#102]
Error message is: We couldn't log you in with the provided details
I am sure password is correct.

The flow was:
authenticate mutation -> copy jwt token into header -> test with viewer query = works fine -> deleteAccount mutation not working with the same password as authenticated.

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/4570510/189298619-e0c8d10f-3367-44a3-94ba-35f2ac10c382.png">

**Comment by jamesedmonston** [comment]
Fixed in https://github.com/jamesedmonston/graphql-authentication/commit/0f695556f03656b0fd1fa6768f27d3f0e63c75dc

**Comment by jamesedmonston** [comment]
Released in `2.1.0`!
