### ISSUE TITLE
Viewer query throws authorization error

### ISSUE THREAD

**Issue by brimby** [jamesedmonston/graphql-authentication#104]
Here's what happens when I try to run the simple Viewer query
<img width="899" alt="Screen Shot 2022-09-16 at 6 11 20 PM" src="https://user-images.githubusercontent.com/20480908/190814273-0fea889b-1581-4651-b2fc-926309f46691.png">

All my other queries and mutations run fine from the same schema:
<img width="912" alt="Screen Shot 2022-09-16 at 6 11 40 PM" src="https://user-images.githubusercontent.com/20480908/190814317-6b0da915-5d4f-4471-9eda-92f2f29dbe1a.png">

I imagine few people use the Viewer query, did it slip through the cracks at some point? Thanks.

**Comment by jamesedmonston** [comment]
Have you followed the instructions [here](https://graphql-authentication.jamesedmonston.co.uk/usage/signing-requests)?
