### ISSUE TITLE
updateViewer not working on entry field

### ISSUE THREAD

**Issue by J-Protz** [jamesedmonston/graphql-authentication#106]
Hi! Been using this plugin for a long time and it works flawlessly for my other needs, however I am trying to save a list of entries to a user's account, and it seems to be failing but not erroring.

This is the authenticated query I send, it is written in JS using a grqphQL package where the second argument is the vars.

I also tried the same query, but simply updating the user's firstName. This worked perfect.

```js
const entrySaves = [1,2,3];
gql.request(
            gql`
                mutation saveEntry($entrySaves: [Int]) {
                    updateViewer(entrySaves: $entrySaves) {
                        firstName
                        ... on User {
                            entrySaves {
                                id
                            }
                        }
                    }
                }
            `,
            entrySaves
        )

```

This simply returns the same array of ID's that the user already has, and does nothing. I have tried everything, and it errors out in every other set up I can imagine. I'm somewhat new to gql mutations, and rely heavily on trial and error as well as the craft gql explorer, so please let me know if there's anything obvious I'm missing, however this is the same way I save a list of entries to other entries and it works perfect( an array of ids).

I've allowed mutations and queries on all fields,  and in the schema everything is selected. I did note that on the user section of the schema, it's simply empty, which seems odd to me. Not sure if related.

I know this isn't your problem, but this is for a fast approaching deadline, any help would be extremely appreciated.

I've looked through all of the documentation and previous issues.

**Comment by J-Protz** [comment]
Update, i forgot how to pass variables!
 This works

```js
const variables = {
    entrySaves =:[1,2,3]
}

gql.request(
            gql`
                mutation saveEntry($entrySaves: [Int]) {
                    updateViewer(entrySaves: $entrySaves) {
                        firstName
                        ... on User {
                            entrySaves {
                                id
                            }
                        }
                    }
                }
            `,
            variables
        )

```

**Comment by jamesedmonston** [comment]
@J-Protz glad you got it working! Happy to help with any other issues/questions.
