### ISSUE TITLE
[feature request]: password-less login

### ISSUE THREAD

**Issue by magicspon** [jamesedmonston/graphql-authentication#107]
Heyo,

I've nay idea if this is remotely possible.  But a magiclink/passwordless login provider would be fricking awesome.

Feel free to put a bag over this ticket and pull the trigger ;)

**Comment by jamesedmonston** [comment]
Would you expect this to integrate with a 3rd party, or do you think a simple email with a link that contains a code which the plugin verifies would be secure enough?

Would you expect the `authenticate` mutation to trigger this, or to have a separate mutation (e.g. `authenticatePasswordless`)?

**Comment by magicspon** [comment]
A first party solution would be ideal. Although i'm sure having the option to use a third party provider would be nice.  

Regarding security... sorry I've no idea what the security implications of a email + code would be.  I would presume it would be okay, but I'm no authority on security.

>Would you expect the authenticate mutation to trigger this, or to have a separate mutation (e.g. authenticatePasswordless)?

I don't have a strong opinion either way. A separate mutation would work for me.

**Comment by jamesedmonston** [comment]
@magicspon made good progress on this last night. Will potentially have a release out this evening

**Comment by jamesedmonston** [comment]
@magicspon I've just pushed the initial version of this to the `develop` branch. Would you be able to pull from there and check if it's working as you'd expect?

I haven't written any documentation yet, but all you need to do is use the `sendMagicLink` and `verifyMagicCode` mutations.

The email that's sent out is editable in the `System Messages` settings in utilities.

**Comment by jamesedmonston** [comment]
@magicspon I've done some testing and have just pushed it out in `2.3.0`! Hope you find it useful 👍

You can see the docs [here](https://graphql-authentication.jamesedmonston.co.uk/usage/magic-authentication).
