### ISSUE TITLE
Error on save for the plugin options when we select "never" for expiration option 

### ISSUE THREAD

**Issue by ipatate** [jamesedmonston/graphql-authentication#11]
Sorry James. I found an error when i save the configuration plugin. If i use "Never" for expiration, i can't save without error.

**Comment by jamesedmonston** [comment]
@ipatate On it – thanks for reporting

**Comment by jamesedmonston** [comment]
@ipatate I've just released [`1.18`](https://github.com/jamesedmonston/graphql-authentication/releases/tag/1.1.8) which fixes this
