### ISSUE TITLE
AWS cognitio support 

### ISSUE THREAD

**Issue by jubalj** [jamesedmonston/graphql-authentication#111]
Hi James,

I'm using AWS cognitio with a Vuejs front-end is there a way I can use the retuned jwt with your plugin to authenticate with craft? There are unmaintained plugins that offer this functionality (https://plugins.craftcms.com/craft-cognito-auth) does this plugin offer similar functionality?

Sorry if I'm misunderstanding the purpose of the plugin!

Cheers
Jubal

**Comment by jamesedmonston** [comment]
@jubalj I'm not familiar with AWS Cognito, so not fully sure what you're looking to do. Would you be able to elaborate on what exactly it is you're trying to achieve, and how you expect the plugin to facilitate that? Thanks!
