### ISSUE TITLE
Craft 4: Can't automatically activate users

### ISSUE THREAD

**Issue by milesjbland** [jamesedmonston/graphql-authentication#112]
Hey @jamesedmonston!

I noticed when upgrading to Craft 4 (4.2.7) and the latest version of this plugin (2.1.2), users are no longer automatically activated when created via the `register` mutation.

Our user settings currently look like this:

<img width="883" alt="Screenshot 2022-10-17 at 17 23 17" src="https://user-images.githubusercontent.com/12896561/196230947-2de3c66e-ecd2-45f1-b01a-e7317f93a988.png">

Am I missing anything?

**Comment by Stalex89** [comment]
Can confirm the issue, when creating user via the `register` mutation, the status of the new user is `inactive`, and I'm getting the `Error: Please activate your account before logging in` message until I will manually activate it in Craft.

Screenshots of my settings:

<img width="757" alt="Screenshot 2022-10-25 at 19 26 14" src="https://user-images.githubusercontent.com/23526237/197841761-6bee510e-4e64-410b-bef4-fb7d9bf92e8b.png">

<img width="1004" alt="Screenshot 2022-10-25 at 19 26 31" src="https://user-images.githubusercontent.com/23526237/197841800-472169b8-ec08-4643-bee2-88b686cd2fec.png">
