### ISSUE TITLE
Deleting users isn't working

### ISSUE THREAD

**Issue by brimby** [jamesedmonston/graphql-authentication#115]
When trying to delete a user I was getting the error `Cannot query field \"deleteAccount\" on type \"Mutation\".`

Since I was using your mutation code directly from the docs I figured there was perhaps a typo in the docs, so I searched "deleteAccount" in the codebase to see if I could find the syntax you used, but it turns out that "deleteAccount" is never mentioned in the codebase anywhere. So I tried searching just simply "delete" and I only found things related to deleting tokens.

Did the code for deleting users get lost somewhere or am I losing my head?

**Comment by brimby** [comment]
I was using this mutation (even the hardcoded password because I was going to work it out in steps):
`mutation DeleteAccount {
  deleteAccount(
    password: "testing1234"
    confirmPassword: "testing1234"
  )
}`

**Comment by brimby** [comment]
Oh I see now, you have it on Craft 4 but not 3. Any chance you're going to add it to 3 or is it just time I upgraded?

**Comment by brimby** [comment]
I brought the deleteAccount code over into my Craft 3 project locally and it works. I'd send a pull request except I'm not sure if/how I can send a pull request for a v1 change rather than a v2 change. Sorry I'm not super good with github. If there is a way to submit a pull request for the Craft3 compatible branch/fork, let me know and I'll send it along.

If it's not possible, then I'm fine just running my custom code locally.

**Comment by jamesedmonston** [comment]
@brimby I'm backporting some Craft 4 changes that we need internally for work on a Craft 3 site, so I can bring across this mutation. I'll try and get that done over the next week or so.

Thanks!

**Comment by brimby** [comment]
Are you still planning on backporting this? If you're wanting to bail on Craft 3, I understand. I'm just trying to make a plan. If you'd like me to send you my repo zip where I implemented this locally, I can. I just don't know how to make a pull request for the 1.0 version of the project (is that possible?)
