### ISSUE TITLE
Wrongly linked settings in nav bar

### ISSUE THREAD

**Issue by robinbeatty** [jamesedmonston/graphql-authentication#117]
Noticed the Settings breadcrumb link in the cp nav bar in `https://mycraftapp.com/admin/graphql-authentication/settings` is wrongly linked and points to `https://mycraftapp.com/settings`

**Comment by jamesedmonston** [comment]
@robinbeatty is this on Craft 3 or 4?

**Comment by robinbeatty** [comment]
Sorry yes craft 4@latest and latest version of plug-in. Sounds like just a missing / in uri

**Comment by jamesedmonston** [comment]
<img width="710" alt="Screenshot 2023-01-07 at 14 55 56" src="https://user-images.githubusercontent.com/4851924/211156788-4045a7f5-add3-42a3-9c76-b2b91e3890d6.png">

@robinbeatty Are you referring to the highlighted (in blue) settings link here? This seems to follow Craft's conventions. If you go into fields -> a field, clicking settings goes back to `/settings`.

**Comment by robinbeatty** [comment]
Should it not point to `/admin/settings` rather than `/settings`?
I am getting a 404 from no `/settings` route when clicking this...

**Comment by jamesedmonston** [comment]
@robinbeatty oops! That makes sense – I've got my local plugin test site set up without a CP trigger. Fixed for `2.2.1`
