### ISSUE TITLE
Feature request - 2FA

### ISSUE THREAD

**Issue by anchovy** [jamesedmonston/graphql-authentication#118]
Hi, looking to use this plugin on a new headless craft v4 site we're developing but we also require 2FA, is this on the roadmap at all?

**Comment by jamesedmonston** [comment]
@anchovy good idea. I'll have a think about how best to integrate it. Thanks!

**Comment by jamesedmonston** [comment]
Will be releasing this shortly. Just need to sort the docs.

**Comment by jamesedmonston** [comment]
Released in 2.5.0!
