### ISSUE TITLE
GraphQL Authentication choosing wrong schema when applying field rules 

### ISSUE THREAD

**Issue by danieltott** [jamesedmonston/graphql-authentication#119]
## Problem:

When querying the graphQL endpoint not as a logged-in user via GraphQL Authentication, but just using a Craft GraphQL schema token (via `Authorization: Bearer ....`), GraphQL Authentication is still applying the field rules but applying rules from the wrong Schema (seems to be always using Public).

I would expect GraphQL Authentication to either ignore requests that aren't coming through the JWT auth, or choose the correct Schema.

<dl>
<dt>Craft Version</dt>
<dd><code>Craft Pro 4.3.6.1</code> (latest at this time)<dd>
<dt>GraphQL Authentication version</dt>
<dd><code>2.3.0</code> (latest at this time)</dd>
</dl>

![image](https://user-images.githubusercontent.com/360261/214342003-7d9a7570-d0cb-4f2c-9c1f-0a68047f6747.png)

## To reproduce:

I've created [a reproduction repo](https://github.com/danieltott/craft-gql-bug) with instructions on how to recreate this bug - it's pretty straight forward.

To recreate on your own setup:

- Create a GraphQL Schema that has access to entries with the field in question
- In GraphQL Authentication -> Settings -> Fields, set the field to Private with the Public Schema, but Query/Mutate in the new Schema
- Test that the query works in GraphiQL
- Make a request to the GraphQL endpoint querying that field with a `Authorization: Bearer {token}` (**not** the GraphQL Authentication JWT header)

You'll get an error response like this:

```json
{
  "errors": [
    {
      "message": "User doesn't have permission to access requested field(s)"
    }
  ]
}
```

**Comment by jamesedmonston** [comment]
@danieltott fixed in `2.3.1`!
