### ISSUE TITLE
When installing this plugin, GraphiQL won't let us load entries

### ISSUE THREAD

**Issue by BOAWEB** [jamesedmonston/graphql-authentication#12]
After installing the plugin, we get an issue with our public scheme.
When querying for entries, we get the following error:
![image](https://user-images.githubusercontent.com/1536173/99803637-19730d00-2b3a-11eb-89d9-44e664059daa.png)

What could be the problem?

**Comment by jamesedmonston** [comment]
@BOAWEB I'll look into getting a fix out for this over the weekend.

In the interim you can get around it by:
- Creating a separate schema with the same permissions as your public one
- Create a token that's assigned to the new schema
- Use the token to authorise the calls (`Authorization: Bearer ${token}`)

Thanks!

**Comment by jamesedmonston** [comment]
@BOAWEB Follow up question, are you using GraphiQL through the Craft admin? It _should_ be allowing queries from that URL even without an authorization header. Is your GraphiQL hosted at `/graphiql`?

**Comment by BOAWEB** [comment]
Yes, we are using GraphiQL through the Craft admin and it is hosted at `/admin/graphiql`

**Comment by jamesedmonston** [comment]
@BOAWEB I can't seem to replicate this issue.

Did you authenticate a user from GraphiQL, with the `HTTP-Only cookie` option enabled? Would you be able to check the network request and see if you've got a token being passed in the cookies?

**Comment by BOAWEB** [comment]
Hi James,
Sorry, we already decided not to go along this path.
