### ISSUE TITLE
Users randomly have `accessCp` permission given.

### ISSUE THREAD

**Issue by james-em** [jamesedmonston/graphql-authentication#120]
Hi,

We have a client who is using this Graphql-Authentication plugin and is having an issue with users having randomly the role `accessCp` granted. I kept digging in there codebase until I was forced to look deeper in the libraries and hit this plugin.

From a quick look, I already have found one instance where the user could be granted permanently the `accessCp` permission:

Here the error is being thrown before restoring the proper user permissions.

https://github.com/jamesedmonston/graphql-authentication/blob/develop/src/services/UserService.php#L146

**Comment by jamesedmonston** [comment]
Thanks. I’ll get this fixed

**Comment by jamesedmonston** [comment]
@james-em fixed in `2.3.1`!
