### ISSUE TITLE
Authenticate by username

### ISSUE THREAD

**Issue by anchovy** [jamesedmonston/graphql-authentication#126]
Hi, Any any to authenticate by username rather than email?
Or - can we add another field to authenticate by as well, so we pass in 3 variables, email, password, client number.

**Comment by jamesedmonston** [comment]
You should be able to pass the username into the `email` field. The authenticate mutation calls Craft’s `getUserByUsernameOrEmal` method: https://github.com/jamesedmonston/graphql-authentication/blob/develop/src/services/UserService.php
