### ISSUE TITLE
Validating JWT token from another module/Yii app - Question

### ISSUE THREAD

**Issue by anchovy** [jamesedmonston/graphql-authentication#127]
Hi

We're using your plugin to log in users for a headless app - we're also running a restful api in a separate Yii app (has access to the craft database and files).

So - my question is, can we validate the token sent from the headless app in the Yii api against the logged-in user in craft?

Thanks in advance.

**Comment by jamesedmonston** [comment]
Closing this for now. Happy to re-open if that method doesn't work in your case! Thanks.
