### ISSUE TITLE
Reset password and Activate account custom target URL

### ISSUE THREAD

**Issue by scoch5** [jamesedmonston/graphql-authentication#128]
HI,
I'm using the plugin for a headless site, everything works perfectly but I have some problems with the emails that are sent for activation and password reset.
The email that is sent contains the link to /admin/set-password?code=XXX where the base URL is the frontend site. Can I change the baseURL of this request or change the path /admin/ ?

**Comment by jamesedmonston** [comment]
Are you able to use https://craftcms.com/docs/3.x/config/config-settings.html#setpasswordpath and/or https://craftcms.com/docs/3.x/config/config-settings.html#verifyemailpath?
