### ISSUE TITLE
Forgotten password - triggers reset password for suspended users.

### ISSUE THREAD

**Issue by anchovy** [jamesedmonston/graphql-authentication#134]
We've got users who are suspended and therefore not allowed to login into the app (and therefore not reset their password).
But if they go through the forgotten password loop via the ForgottenPassword mutation it sends them the reset password token, allowing them to reset their password and then activate their account?

```
{"query":"\n    mutation ForgottenPassword($email: String!) {\n  forgottenPassword(email: $email)\n}\n    ","variables":{"email":"SUSPENDED_USER@EMAIL.COM"}}
```

Couple of solutions
1: Throw an error (make it editable) i.e. Your account is suspended, you cannot reset your password.
2: Have a BEFORE_PASSWORD_REST event so we can hook into it and return false.

**Comment by jamesedmonston** [comment]
Fixed in https://github.com/jamesedmonston/graphql-authentication/commit/1bc31c2ff154aa534bd75a4600c985e444278ce9
