### ISSUE TITLE
No longer works after updating to Craft 4.5.2

### ISSUE THREAD

**Issue by jstevens79** [jamesedmonston/graphql-authentication#135]
I get a 403 error after updating to Craft 4.5.2. I'm digging into this further, but wanted you to be aware.

**Comment by jamesedmonston** [comment]
Thanks for the heads up. I’m away this weekend so won’t be able to look into this until next week I’m afraid!

**Comment by epapada** [comment]
Same here - running Craft 4.5.5. Does anyone know up to which craft version works? so that I can downgrade.

Cheers

**Comment by BrandonJamesBorders** [comment]
I was having this issue as well but after looking in the logs I figured out I needed to enable this in the public GraphQL schema. 

![image](https://github.com/jamesedmonston/graphql-authentication/assets/6044898/d90c85b6-c85e-43c9-a45f-9db156573c0b)

I didn't change anything else and that got it working.

**Comment by jstevens79** [comment]
> I was having this issue as well but after looking in the logs I figured out I needed to enable this in the public GraphQL schema.
> 
> ![image](https://user-images.githubusercontent.com/6044898/269255787-6b853d32-67b4-431f-9020-6c112f608f1f.png)
> 
> I didn't change anything else, and that got it working.

Perfect! This got me up and going again. Thank you!

**Comment by degraaf** [comment]
Also just got this error after a Craft version update.

@jamesedmonston, I can see this has occurred because Craft added the `_enforceSiteAccess` method to the GraphQL controller which fires before the plugin's event for `setActiveSchema`.

Do you think the plugin's approach will be updated or whether the above workaround will be required on a more permanent basis? Interested to know the outcome.

**Comment by jacobgraf** [comment]
@jamesedmonston Why did this get closed? Was there resolution? I believe this is the same issue I'm having on my other issue (#155). I've lost like 3 full hours of working trying to figure this out. Can you give some more clarity to what's going on here and why and what the official fix is, and why? I went through the docs multiple times and don't see anything related this this bug or how to fix it.
