### ISSUE TITLE
2FA - Add a separate mutation for disabling 2FA

### ISSUE THREAD

**Issue by Stalex89** [jamesedmonston/graphql-authentication#136]
Hi @jamesedmonston,

Thank you very much for making 2FA possible with the plugin. 

Is it possible to add an extra mutation to disable 2FA for user? something like this: 

```
mutation disableTwoFactor {
  disableTwoFactor(
    email: "james@testingthings.com"
    password: "testing123"
    code: "123456"
  ) {
    twoFactorEnabled
  }
}

// returns
{
  "data": {
    "twoFactorEnabled": false
  }
}
```
Thank you in advance!

**Comment by jamesedmonston** [comment]
@Stalex89 Looks like I forgot to document the disable mutation... https://github.com/jamesedmonston/graphql-authentication/blob/develop/src/services/TwoFactorService.php#L201-L239
