### ISSUE TITLE
Invalid Authorization Header when using googleSignIn

### ISSUE THREAD

**Issue by blnkt** [jamesedmonston/graphql-authentication#146]
Using:
```
"craftcms/cms": "4.7.3"
"jamesedmonston/graphql-authentication": "2.5.0"
```

My set up does have `Permission Type` set to `Multiple Schemas` in the plugin settings, but I've omitted the user group specific mutation names below for clarity.

After successfully exchanging an auth `code` with Google for a User's `idToken` I use the `googleSIgnIn` mutation as follows:
```
mutation GoogleSignIn {
  googleSignIn(idToken: "THE_ID_TOKEN") {
    jwt
    jwtExpiresAt
    refreshToken
    refreshTokenExpiresAt
    user {
      id
      status
    }
  }
}
```

I am also including the same `idToken` in the `Authorization` header of the request like:
```
Authorization: JWT ${idToken}
```

And as recommended in the Craft docs (and referenced in your docs), my `.htaccess` file includes:
```
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

**However, the response I get from Craft is the error message `[GraphQL] Invalid Authorization Header`**

If I omit the Authorization header, the response I get from Craft is your plugin's "Forbidden Mutation" error message.

**For this initial sign in/up mutation, am I correct in using the `idToken` as the JWT to sign requests to Craft?  Is there another token I should be using (Google gives me `access_token`, `refresh_token`, and `id_token` to choose from)?  Is signing the request with JWT required at all in this initial sign in/up mutation?**

**Comment by jamesedmonston** [comment]
The `idToken` value shouldn't be passed into the `Authorization` header – you pass it in to the `googleSignIn` mutation, and then use the `jwt` value from the response inside the auth header.
