### ISSUE TITLE
Craft CMS 5 compatibility 

### ISSUE THREAD

**Issue by mgambella** [jamesedmonston/graphql-authentication#149]
With Craft CMS 5 released, I wanted to check if this is going to be updated for the new version.

**Comment by robinbeatty** [comment]
How’s it going with Craft 5? We’re pretty dependent on this plugin and looking forward to craft 5 edition. Any sense of timescale? Thanks

**Comment by DTesch-Reem** [comment]
Was also wondering.
I really need this plugin for Craft 5

**Comment by jamesedmonston** [comment]
Will try to get something out this weekend – @brandonkelly has sorted most of it in https://github.com/jamesedmonston/graphql-authentication/pull/151 🎉

**Comment by sir-savien** [comment]
Any timeline updates on this topic? I'd really like to start a project soon but my choice between craft4/craft5 or another CMS altogether depends on the availability of this plugin.

**Comment by jamesedmonston** [comment]
Working through this now everyone. Big thanks to @brandonkelly for sorting the initial PRs

**Comment by jamesedmonston** [comment]
You can now test it by installing the `develop` branch [through Composer](https://lornajane.net/posts/2014/use-a-github-branch-as-a-composer-dependency).

Currently, 2FA is disabled, and named section queries aren't restricting to the authed user – i.e. if you have a channel called `Page`, the `pageEntries` query won't be restricted. You can use the following query for restricted access, though:

```graphql
query Entries {
  entries(section: "page") {
    ...
  }
}
```

I will try to work on updating the 2FA implementation to use Craft's built-in stuff, and work out a way to restrict the name queries.

**Comment by mrbenito** [comment]
> Any updates on a stable version?

I would also like to know. We've got a few clients seeking to upgrade to Craft5. Thanks in advance.

**Comment by chrisrowe** [comment]
Thanks for your work on this, I'm waiting on the C5 version also but having difficulty even installing with `dev-develop` (and `--with-all-dependencies`) on a relatively vanilla Craft installation.

```
  Problem 1
    - jamesedmonston/graphql-authentication[dev-craft3, 1.0.0, ..., 1.12.3] require craftcms/cms ^3.5.0 -> found craftcms/cms[3.5.0-beta.1, ..., 3.x-dev] but it conflicts with your root composer.json require (5.2.3).
    - jamesedmonston/graphql-authentication dev-develop requires lcobucci/jwt ^5.3.0 -> found lcobucci/jwt[5.3.0, 5.3.x-dev, 5.4.x-dev] but these were not loaded, likely because it conflicts with another require.
    - jamesedmonston/graphql-authentication[dev-master, 2.0.0, ..., 2.5.0] require craftcms/cms ^4.0.0-alpha.1 -> found craftcms/cms[4.0.0-alpha.1, ..., 4.x-dev] but it conflicts with your root composer.json require (5.2.3).
    - Root composer.json requires jamesedmonston/graphql-authentication * -> satisfiable by jamesedmonston/graphql-authentication[dev-master, dev-craft3, dev-develop, 1.0.0, ..., 1.12.3, 2.0.0, ..., 2.5.0].
```

**Comment by jpcarpenter** [comment]
Eagerly awaiting this plugin for Craft 5. Any word on the latest?

**Comment by mrbenito** [comment]
Honestly it's outrageous this feature isn't handled directly by @pixelandtonic Pixel and Tonic. James is doing god's work, but cmon, our entire headless authentication solution shouldn't rest on one man. Our firm has made the decision to just NOT move to the next version of craft for 12 months so guys like James has plenty of time to get around to updating this kind of thing.

**Comment by jamesedmonston** [comment]
Sorry for the delay everyone.

I've finalised the remaining pieces (2FA and named section query restrictions) and fixed a couple of issues.

Sorting out a `3.0.0-RC1` release now.

**Comment by chrisrowe** [comment]
@jamesedmonston Thanks for all your hard work on this!

**Comment by mrbenito** [comment]
👏👏👏👏
