### ISSUE TITLE
Last login not updating on users

### ISSUE THREAD

**Issue by jamesedmonston** [jamesedmonston/graphql-authentication#2]
Currently the `register` and `authenticate` mutations aren't updating the 'last login' field on users, so they'll be blank unless they log in to the control panel directly.

**Comment by jamesedmonston** [comment]
Fixed in https://github.com/jamesedmonston/graphql-authentication/commit/8d51c41cbe7caaa6e9a3bed85ba0146581595fe7

**Comment by jamesedmonston** [comment]
Interestingly we're not having this issue on our production client projects 🧐 

Are you still seeing the issue on the latest Craft version?

![Screenshot 2021-11-11 at 11 03 36](https://user-images.githubusercontent.com/4851924/141287427-fd1cb718-2a43-432d-b424-ddb58cf7be3f.png)

**Comment by magicspon** [comment]
Snap... looks like it's fixed itself.

cheers
