### ISSUE TITLE
[Bug] "Undefined offset" when doing mutations

### ISSUE THREAD

**Issue by menberg** [jamesedmonston/graphql-authentication#21]
Thanks for this wonderful plugin. I'm hitting an error though when doing mutations.

The bug is located in [TokenService.php](https://github.com/jamesedmonston/graphql-authentication/blob/d6cd388bf41b5ee8c003ed21bbe4287ee5a81e0e/src/services/TokenService.php#L133) inside `_extractUserId(GqlToken $token)`.

I get `Undefined offset: 1` PHP error when running `return explode('-', $token->name)[1];`

XDebugger shows that `$token->name` equals `"userToken"` with neither a dash or userId. So exploding `$token->name` returns only a single value array. That's why it throws with `Undefined offset: 1` and aborts the request.

What would be a good approach to bugfix this issue?

Thanks!

**Comment by jamesedmonston** [comment]
@menberg huh, that's strange! Thanks for reporting.

Do you have a token called `userToken` in `/admin/graphql/tokens`?

Are you using a token created through the plugin to authorise your calls, or one you created manually?

**Comment by jamesedmonston** [comment]
@menberg would you be able to try the latest commit in the `develop` branch (https://github.com/jamesedmonston/graphql-authentication/commit/0ee363be19813bed279762773e04c8435a989b74) and see if the issue persists? Thanks!

**Comment by menberg** [comment]
Hey James, that was quick. I just applied the latest `develop` branch and the problem seems to be successfully fixed. I'm amazed! Thanks a lot.

**Comment by jamesedmonston** [comment]
@menberg okay great! Glad to hear it's fixed!
