### ISSUE TITLE
Possible issue: Double-packed array found

### ISSUE THREAD

**Issue by menberg** [jamesedmonston/graphql-authentication#22]
When running `./craft utils/repair/project-config` I get the following output:
```
Repairing project config ...
- double-packed array found at plugins.graphql-authentication.settings.entryMutations
- double-packed array found at plugins.graphql-authentication.settings.entryQueries
- double-packed array found at plugins.graphql-authentication.settings.granularSchemas
- double-packed array found at plugins.graphql-authentication.settings.granularSchemas.group-1
Finished repairing project config
```

Not sure but might be related to https://github.com/craftcms/cms/issues/5525#issuecomment-644420787 and how data is stored in the plugin settings model as described on https://craftcms.com/docs/3.x/extend/plugin-settings.html#settings-model: _any complex or nested data types that aren’t compatible with toArray() should be excluded from fields() and declared in extraFields() instead._

Are those project config warnings above reason enough to consider this a bug?

**Comment by jamesedmonston** [comment]
@menberg Interesting, thanks for spotting that – and thanks for the references! I'll have a look 👍🏻

**Comment by jamesedmonston** [comment]
@menberg I haven't found suitable way to silence this warning. I followed the advice in your references, but I couldn't get it to stop saving them into project config as associative arrays.

I don't think it's actually an issue (see [here](https://github.com/craftcms/cms/issues/6317#issuecomment-659056509)), and I haven't received any bug reports of project config not syncing across environments.

I'm going to close this issues, but I will be more than happy to take another look should it stop syncing/saving properly.

Thanks!
