### ISSUE TITLE
Invalid Authorization Header

### ISSUE THREAD

**Issue by approached** [jamesedmonston/graphql-authentication#23]
Hi @ all

I just quick install this plugin and tried to use. Now i become on every request an error with a **anonymus/guest/no barear token** user.

Response:
```json
{
  "errors": [
    {
      "debugMessage": "Invalid Authorization Header",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "entries"
      ]
    }
  ],
  "data": {
    "entries": null
  }
}
```

After i disabed this plugin. It works great again. BTW: the graphQL dashboard doesn't work too.
Has anybody a idea?

**Comment by jamesedmonston** [comment]
@approached Would you be able to try running the latest commit from the `develop` branch to see if that fixes it? I've made a couple fixes in that branch that I'll be bundling into a release very soon.

**Comment by jamesedmonston** [comment]
@approached I've just released [`1.2.1`](https://github.com/jamesedmonston/graphql-authentication/releases/tag/1.2.1) which resolves this.

**Comment by approached** [comment]
![Screenshot 2020-12-02 at 15 02 45](https://user-images.githubusercontent.com/3439330/100882821-e4f33f80-34af-11eb-8ead-2ddbd46e406d.png)

It is not working as aspected.

**Comment by jamesedmonston** [comment]
@approached Damn! Sorry about this. I will take another look.

**Comment by approached** [comment]
I have tried both. For me it's not clear for what this setting will used `Use HTTP-Only cookie`

I use as fronted nextjs. But it is not really clear how i can build a login/authentication process. JWT would be nice but no documation available.

Quick question, how i can refresh the token?
If i store the token in a local storage, does me need `Use HTTP-Only cookie` enabled?

**Comment by jamesedmonston** [comment]
@approached I'm just about ready to release an update which includes proper JWT and refresh token support. If you run the latest commit in the `develop` branch you should be able to get started with this.

I've rewritten the documentation using Docusaurus which includes more examples and explanations. This can be found here: https://graphql-authentication.jamesedmonston.co.uk

**Comment by jamesedmonston** [comment]
@approached I just managed to replicate this in a client project, and have pushed version `1.3.1` that _actually_ fixes the issue. Sorry for the hassle!

**Comment by daltonrooney** [comment]
@jamesedmonston I'm experiencing this error on my front-end I wonder if it might be a conceptual problem on my part that could be cleared up with some documentation.

Can you confirm that _all GraphQL requests must be authenticated_ when the plugin is active? I.e. no more public schema requests or Bearer token requests that reference a schema directly?

For my front-end, I've been working with the idea that most of the pages will be public and therefore wouldn't need to be authenticated. Then there's an "admin" section with protected routes where an authenticated user would have access to some non-public sections and mutations.

But if _all_ requests must be authenticated, I guess I would have to create an anonymous user account and authenticate with that during build-time and for anonymous web users, correct?

**Comment by jamesedmonston** [comment]
@daltonrooney Damn.

> Can you confirm that all GraphQL requests must be authenticated when the plugin is active? I.e. no more public schema requests or Bearer token requests that reference a schema directly?

This _shouldn't_ be the case, but maybe the logic is broken somewhere. The intended functionality is that any requests against the public schema are left untouched.

> But if all requests must be authenticated, I guess I would have to create an anonymous user account and authenticate with that during build-time and for anonymous web users, correct?

In the interim, you could create a schema that matches your public one, and create a token that's assigned to the new schema, then use that token to authorise your build-time calls.

If you go to https://graphiql-online.com, put in your endpoint, and run a public query, do you get the error?

**Comment by daltonrooney** [comment]
@jamesedmonston Yeah I've got JWT enabled, and I'm able to successfully authenticate with a Google ID token and get a JWT token back. 👍 But I do think something weird is going on with the public query:

![public query (internal)](https://user-images.githubusercontent.com/742045/101394476-6e728b00-387d-11eb-8823-5047013be872.png)

![public query (external)](https://user-images.githubusercontent.com/742045/101394497-74686c00-387d-11eb-914f-68cbfd88b515.png)

(the graphiql-online.com query works when the plugin is disabled)

**Comment by jamesedmonston** [comment]
@daltonrooney Okay I've just worked out the issue. It was a bit of an oversight in the logic on my part. https://github.com/jamesedmonston/graphql-authentication/commit/89d2b778859bc2b937e037fcf9cdf38047b06e41 should fix it.

Sorry for the annoyance guys.

**Comment by daltonrooney** [comment]
@jamesedmonston This seems to be working correctly now. I'm able to query the public API as well as use existing tokens with no problem. Thanks so much for the help!
