### ISSUE TITLE
Google Authentication error: Undefined index: family_name

### ISSUE THREAD

**Issue by daltonrooney** [jamesedmonston/graphql-authentication#25]
I believe my Google profile does not have the `family_name` value set, I'm getting this error when trying to use Google auth:

```
{
  "errors": [
    {
      "debugMessage": "Undefined index: family_name",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "googleSignInUsers"
      ]
    }
  ]
}
```

**Comment by jamesedmonston** [comment]
@daltonrooney I've just added some fallbacks in that should hopefully resolve this: https://github.com/jamesedmonston/graphql-authentication/commit/920f5eb343c7bdeea8c3438fc6038da4555ee4c1

**Comment by daltonrooney** [comment]
Thanks, works for me!
