### ISSUE TITLE
No results on JWT authenticated request

### ISSUE THREAD

**Issue by daltonrooney** [jamesedmonston/graphql-authentication#28]
This may be related to #23 but just in case it's a separate issue I'll post it here. I'm getting no results on my authenticated requests, even though the underlying schema should have the correct access. Here's an overview of what's happening, let me know if this makes sense or if I've missed anything:

- I have a GraphQL schema called "Website" which gives access to all of the public sections of the website.
- I've created a token for the Website schema.
- I'm able to call my query with the token and get the expected response (Screenshot 1)

Next, I've enabled the GraphQL Authentication plugin and set up the "Multiple Schemas" permission type. 
- I've got a group called "Users" with no CP access, which are mapped to the "Website" schema. (Screenshot 2)
- I use the `GoogleSignInUsers` mutation with my idToken to get a JWT token (Screenshot 3).
- I use the JWT token with the same query, which appears to run successful but returns an empty result (Screenshot 4).

Any thoughts on what could be happening here? 
![screenshot 1](https://user-images.githubusercontent.com/742045/101407050-2b211800-388f-11eb-920a-7a4617028a53.png)
![screenshot 2](https://user-images.githubusercontent.com/742045/101407059-2e1c0880-388f-11eb-9633-b5d8229bf191.png)
![screenshot 3](https://user-images.githubusercontent.com/742045/101407056-2d837200-388f-11eb-8fcc-8bb8d59a618c.png)
![screenshot 4](https://user-images.githubusercontent.com/742045/101407061-2eb49f00-388f-11eb-8eda-5131bcdf0cdf.png)

**Comment by jamesedmonston** [comment]
@daltonrooney thanks for the very in-depth issue!

A couple questions:

1. Does running a simple `ping` query work?

```gql
query {
  ping
}
```

2. If you decode the JWT on https://jwt.io, is does the `schema` value look okay?

3. Does clearing the GraphQL cache have any effect?

Once again, sorry for the inconvenience!

**Comment by daltonrooney** [comment]
Sure thing, and thanks for being so helpful on these issues!

1. Yes, ping works correctly
2. Yes, the correct schema value is encoded.
3. No change.

**Comment by jamesedmonston** [comment]
@daltonrooney Thanks for the quick response.

If you grab the `accessToken` value from the decoded JWT and authorise the request from GraphiQL online request like `Authorisation: Bearer ${token}` does that work correctly?

**Comment by jamesedmonston** [comment]
@daltonrooney I'm able to replicate this locally – debugging now!

**Comment by jamesedmonston** [comment]
@daltonrooney Okay I finally managed to get it working properly. The JWT's decoded access token wasn't being sent to the GraphQL controller properly.

Would you be able to try the latest commit from the `develop` branch, please?

**Comment by daltonrooney** [comment]
Yeah, that seems to have fixed it. Thanks so much!
