### ISSUE TITLE
Don't throw `Invalid Authorization Header` if no auth header is set

### ISSUE THREAD

**Issue by Tam** [jamesedmonston/graphql-authentication#31]
Currently the plugin throws `Invalid Authorization Header` when querying something like `getUser`. Instead it should just return null.

**Comment by jamesedmonston** [comment]
I’m not sure. You’re calling a query that’s expecting authorisation, wouldn’t you want it to return a relevant error?

**Comment by Tam** [comment]
The problem is it's treated as a server error and I'm pretty sure the `debugMessage` that actually says what's wrong isn't returned in production.

**Comment by jamesedmonston** [comment]
@Tam Okay, that makes sense. I'll take a look.

**Comment by jamesedmonston** [comment]
@Tam I've modified the behaviour in https://github.com/jamesedmonston/graphql-authentication/commit/50c2d7732ba5b5b0a1b465d132e915532a4830fe so that the data you're requesting returns `null`, but you still get a helpful error message and code, i.e.:

```gql
query {
  viewer {
    id
  }
}
```

Returns:

```json
{
  "errors": [
    {
      "code": "FORBIDDEN",
      "message": "Invalid Authorization Header",
      "category": "graphql",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "viewer"
      ]
    }
  ],
  "data": {
    "viewer": null
  }
}```
