### ISSUE TITLE
"Invalid Authorization Header" on Logout

### ISSUE THREAD

**Issue by DidoMarchet** [jamesedmonston/graphql-authentication#33]
Hi,
when I try to logout either with deleteCurrentToken or deleteAllTokens  I get this error:

```
{
  "errors": [
    {
      "debugMessage": "Invalid Authorization Header",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "deleteCurrentToken"
      ]
    }
  ]
}
```

Does anyone had the same issue?
Thanks in advance and regards,

Davide

**Comment by jamesedmonston** [comment]
@DidoMarchet hey, thanks for trying out the plugin!

A few questions:
- Have you authorised with a user, and are now using the JWT to sign the calls?
- Do other queries/mutations work when signing with the JWT?
- Where are you sending the requests from?
- Can you double check that the access token hasn't expired?

I'll run some tests myself either way, and see if I can replicate.

Cheers

**Comment by jamesedmonston** [comment]
@DidoMarchet I've just run a few tests and I'm unable to replicate this. I authenticated with a user and ran both the `deleteCurrentToken` and `deleteAllTokens` mutations successfully.

Can you double check you've got a valid JWT, and you're [signing the requests correctly](https://graphql-authentication.jamesedmonston.co.uk/usage/signing-requests)?

Happy to take another look if you can supply any more details!

**Comment by DidoMarchet** [comment]
Hi, sorry for the delay of the answer.
I'm trying mutations from Craft Explorer.
Then I get my authentication without problem.
But If I try (from explorer) to remove token it get me the error.

This Works well
```
mutation MyMutation {
  authenticate(email: "MYACCOUNTMAIL", password: "MYPASS") {
    jwt
    jwtExpiresAt
    refreshToken
    schema
    refreshTokenExpiresAt
  }
  refreshToken {
    jwt
  }
}
```

This not works

```
mutation MyMutation {
  deleteAllTokens
}
```
Surely I'm doing something wrong.
Can you share how do you do the call?

Sorry for the dumb question,

Davide

**Comment by jamesedmonston** [comment]
@DidoMarchet Okay, I think I see what's going on here. You need to sign every call after authenticating with the JWT token.

So, you run the `authenticate` mutation, grab the JWT token, and sign the calls as seen [here](https://graphql-authentication.jamesedmonston.co.uk/usage/signing-requests).

I would recommend using https://graphiql-online.com to test your authentication flows, as you cannot add custom headers through the Craft Explorer. Note: you'll need to add this to your `allowedGraphqlOrigins` property in your Craft `general.php` config, as seen [here](https://docs.craftcms.com/api/v3/craft-config-generalconfig.html#public-properties).

**Comment by jamesedmonston** [comment]
@DidoMarchet I've just recorded a little screencast to walk you through it: https://www.youtube.com/watch?v=JMfE5Mb8S4g

**Comment by DidoMarchet** [comment]
Great!
Really thanks for the support!
And have an happy new year,

regards, Davide
