### ISSUE TITLE
Queries including `authorId` return incorrect results

### ISSUE THREAD

**Issue by daltonrooney** [jamesedmonston/graphql-authentication#34]
I've got a section called `courses` and a schema called `instructors`. When I run a query like this:

```
query coursesQuery {
  entries(section: "courses", authorId: 610, status: null) {
    title
  }
}
```

I should only get back 2 courses. 

It works correctly with the public schema, in GraphiQL explorer (with the `instructors` schema), and from https://graphiql-online.com/graphiql using a token I created for the `instructors` schema.

When I query with a JWT token configured for the same schema I get _all_ courses, not limited by author.

I saw that the JWT token has an access token embedded within it. I tried using that token directly and got the same result (courses not limited by author). But when I disable the plugin, that token _does_ return the correct results.

**Comment by jamesedmonston** [comment]
@daltonrooney Hi again! Should probably mark you as our beta tester in the readme at this point... 😅

Have just pushed a fix for this.

**Comment by daltonrooney** [comment]
Thanks James, this seems to have done the trick!
