### ISSUE TITLE
Unable to set category field on register mutation

### ISSUE THREAD

**Issue by howells** [jamesedmonston/graphql-authentication#35]
I'm not sure where I'm going wrong here, but I seem to be unable to set a category for a given user using the register mutation.

Given this mutation:

```
mutation MyMutation {
  register(email: "ssss@sdfasdfail.com", firstName: "qqq", lastName: "asdfsdf", password: "wesafdasdfsadf", legacyId: 6634, organisation: 6634) {
    jwt
    jwtExpiresAt
    user {
      id
      firstName
      lastName
      legacyId
      organisation {
        id
        title
      }
    }
  }
}
```

The `legacyId` custom field is set to 6634 but the organisation, whose id is 6634 definitely exists, is not set. I've tried `[6634]` and `"6634"` as values, but none of them work. Any ideas where I'm going wrong?

**Comment by jamesedmonston** [comment]
@howells Hey,

I'll take a look at this tomorrow!

Does it throw an error, or simply not update the field's value?

Cheers

**Comment by howells** [comment]
It simply doesn't update. Thanks so much, appreciate it!

**Comment by howells** [comment]
@jamesedmonston hate to chase, but wondered if you had a chance to look into it? I need the functionality in place for a new project I'm due to complete early next week.

**Comment by jamesedmonston** [comment]
@howells I've just pushed a fix for this! I'll probably roll a release this evening, but feel free to pull from https://github.com/jamesedmonston/graphql-authentication/commit/165ec78a3c7f93741001a628bf4773782a068d78 if you need it urgently 👍🏻

**Comment by howells** [comment]
Ace will check it out shortly - thanks

**Comment by jamesedmonston** [comment]
@howells just an FYI, the user type registration has slightly changed as of https://github.com/jamesedmonston/graphql-authentication/commit/f6fb1c6aafe60d91221a1d551cd8d266d908760a, so you'll need to spread the user type in the responses, i.e.:

```
mutation {
  authenticate(
    email: "..."
    password: "..."
  ) {
    user {
      id
      fullName
      ... on User {
        customField
      }
    }
  }
}```

I haven't done extensive testing on pre-3.6 in that commit, so best hold off if you haven't updated yet!

**Comment by howells** [comment]
@jamesedmonston seems to work perfectly, thanks!

**Comment by jamesedmonston** [comment]
@howells I've just pushed `1.4.2` which has this fix in. Cheers!
