### ISSUE TITLE
Plugin prevents all GraphQL calls in Craft CMS 3.6.0.1

### ISSUE THREAD

**Issue by benrnorman** [jamesedmonston/graphql-authentication#36]
Hello,

I recently upgraded from Craft CMS 3.5.18 to 3.6.0.1. Subsequently, all my graphql calls return the following message:

`{
  "errors": [
    {
      "message": "Call to a member function getFields() on string"
    }
  ]
}`

If I uninstall the auth plugin, the graphqls work fine.

I also had to bump my php version in composer from 7.2 to 7.3 for the new Craft update, if that may be the cause.

**Comment by jamesedmonston** [comment]
@benrnorman I've just pushed https://github.com/jamesedmonston/graphql-authentication/commit/f6fb1c6aafe60d91221a1d551cd8d266d908760a which should resolve this. Need to run some more tests to ensure it doesn't break backwards compatibility, but you can pull from that commit in the meantime.

**Comment by jamesedmonston** [comment]
@benrnorman I've just pushed `1.4.2` which has this fix in. Cheers!

**Comment by benrnorman** [comment]
Thank you
