### ISSUE TITLE
Reset password process/flow question

### ISSUE THREAD

**Issue by rjgux** [jamesedmonston/graphql-authentication#37]
Hello! Thanks for this plugin, it's awesome.

I have a question about the 'Forgotten Password' / 'Set Password' flow, to allow a user to reset their password. This may be more of a Craft related question.

The mutation to send a password reset email makes sense to me. What I'm trying to then work out is how to route back to my application URL, with both the `code` and `id` query parameters required to then send/use the 'Set password' mutation.

Customising the `Reset your password` email template in Craft > Utils > System Messages looks like this -

```
Hey {{user.friendlyName}},

To reset your {{systemName}} password, click on this link:

<{{link}}>

If you were not expecting this email, just ignore it.
```

... with `{{link}}` generating a URL that looks like https://craft.test/admin/set-password?code=H6debAyhJ5JdKXbd8WleNhFNNUA6KhE3&id=49acc4ae-53d4-4e50-b553-15ee239ecba4

I'm trying to override `{{link}}` here and instead route to `https://myapplication.test/page?code={{code}}&id={{id}}`. Do you have any suggestions on how best to achieve this? Would using a twig `|replace` filter be the best option here?

Thanks!

**Comment by rjgux** [comment]
Update -

I've worked out if you're an admin user `<{{link}}>` is `{siteUrl}/admin/set-password`

Whereas for other users `<{{link}}>` is `{siteUrl}/setpassword`

So by changing `siteUrl` I can achieve what I need to do, but it would still be useful to know if there are any other options here! :)

**Comment by jamesedmonston** [comment]
@rjgux Hey, thanks for the positive feedback!

> So by changing siteUrl (and having a /setpassword route) I can achieve what I need to do, but it would still be useful to know if there are any other options here! :)

Bingo! What I usually do is have 2 separate URLs in `.env`:

```
DEFAULT_SITE_URL=https://admin.site.com
FRONTEND_URL=https://site.com
```

I then use `FRONTEND_URL` in the site settings, like so:

<img width="1792" alt="Screenshot 2021-02-15 at 23 57 45" src="https://user-images.githubusercontent.com/4851924/108003121-a0c10700-6fe9-11eb-8fb3-b3b82ace75d0.png">

Along with the user-related emails then being correct, it'll also point your 'View Entry' buttons on element indexes to the right URL:

<img width="1792" alt="Screenshot 2021-02-15 at 23 58 26" src="https://user-images.githubusercontent.com/4851924/108003155-bb937b80-6fe9-11eb-84d7-f8965a0d664a.png">

Thanks!
