### ISSUE TITLE
Activate User

### ISSUE THREAD

**Issue by magicspon** [jamesedmonston/graphql-authentication#38]
After a user registers, and then goes to the activate url.  Passing code/id to the set password mutation does not activate the user.  

```graphql
mutation SetPassword($password: String!, $code: String!, $id: String!) {
	setPassword(password: $password, code: $code, id: $id)
}
```

response:
```json
{"setPassword": "Successfully saved password"}
```

Cheers

**Comment by jamesedmonston** [comment]
@magicspon Have just released [`1.4.4`](https://github.com/jamesedmonston/graphql-authentication/releases/tag/1.4.4) which fixes this. Thanks for reporting!
