### ISSUE TITLE
Verify email via GraphQL Authentication

### ISSUE THREAD

**Issue by andrewfairlie** [jamesedmonston/graphql-authentication#41]
Hi @jamesedmonston 

Is it possible to have a mutation that handles verifying emails? They're the URLs in the format of `/verifyemail?code=XYZ` which Craft sends out to new users.

I suspect it would be quite similar to how the `setPassword` mutation accepts the code

Ideally, we'd want our headless frontend handling those so that the backend URL isn't exposed.

Cheers,

Andrew

**Comment by jamesedmonston** [comment]
Hey,

Somebody actually requested this on Discord a short while ago, so thanks for the reminder! I'll get it added 👍🏻

Cheers

**Comment by jamesedmonston** [comment]
@andrewfairlie I've just released `[1.6.0](https://github.com/jamesedmonston/graphql-authentication/releases/tag/1.6.0)` which has a mutation called `activateUser`.

cc @magicspon

**Comment by magicspon** [comment]
@jamesedmonston awesome... thanks

**Comment by andrewfairlie** [comment]
Brilliant! Thank you, James. Super fast.
