### ISSUE TITLE
SQL error 42703 on Postgres when registering a new new user

### ISSUE THREAD

**Issue by bartroelands** [jamesedmonston/graphql-authentication#42]
Hello,

I am evaluating your plugin. When trying out a couple of first command I ran into this issue when registering a new user:

query was:

```
mutation Register {
  register(
    email: "joske.vermeulen@schoooten.be"
    password: "koekoek"
    firstName: "Joske"
    lastName: "Vermeulen"
  ) {
    jwt
    jwtExpiresAt
    refreshToken
    refreshTokenExpiresAt
    user {
      id
      fullName
    }
  }
}
```

Response error:

```
"errors": [
    {
      "debugMessage": "SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"expirydate\" does not exist\nLINE 3: WHERE (expiryDate <= CURRENT_TIMESTAMP) AND (name LIKE \"%use...\n               ^\nHINT:  Perhaps you meant to reference the column \"gqltokens.expiryDate\".",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
...

```

I am running Craft version 3.6.10 on a Postgres 11.10 database. I suspect this error is due to the Postgres update statement.
Seems to be an issue with the expirydate passed on completely lowercase in stead of camelcase. 

I managed to get the Register to work when I adapted the code that failed like below:

Tokenservice line 375:

` $gqlTokens = RecordsGqlToken::find()->where('"expiryDate" <= CURRENT_TIMESTAMP')->andWhere(['like', 'name', '%user-%'])->all();`

Tokenservoce line 383 

`$refreshTokens = RefreshToken::find()->where('"expiryDate" <= CURRENT_TIMESTAMP')->all();`

**Comment by jamesedmonston** [comment]
@bartroelands thanks for reporting. Will get fixed ASAP!

**Comment by jamesedmonston** [comment]
@bartroelands Have just pushed [`1.7.0`](https://github.com/jamesedmonston/graphql-authentication/releases/tag/1.7.0) which has this fix in. Thanks!
