### ISSUE TITLE
Enhanced activation functionality

### ISSUE THREAD

**Issue by andrewfairlie** [jamesedmonston/graphql-authentication#43]
Would it be possible to show a different error message if we can't authenticate because the user hasn't yet activated their screen? Also, would it be possible to have a mutation that triggers the activation email being sent?

With these two, we would be able to show a message like

```
You're not yet activated, check your email and click the link to verify your account or <a>click here to resent that email</a>
```

**Comment by jamesedmonston** [comment]
@andrewfairlie I've just pushed a commit that adds a (customisable) response for unactivated users.

![Screenshot 2021-03-15 at 17 05 06](https://user-images.githubusercontent.com/4851924/111192109-a130cb80-85b0-11eb-8160-11b699ca6869.png)
![Screenshot 2021-03-15 at 17 05 04](https://user-images.githubusercontent.com/4851924/111192113-a2fa8f00-85b0-11eb-84a3-436814aa4440.png)

Will look into adding a separate mutation now.

**Comment by jamesedmonston** [comment]
@andrewfairlie I've just pushed another commit which adds a `resendActivation` mutation which takes an `email` argument.

I'm going to fix https://github.com/jamesedmonston/graphql-authentication/issues/42 and then I'll roll out a release.

Cheers

**Comment by jamesedmonston** [comment]
@andrewfairlie Have just pushed [`1.7.0`](https://github.com/jamesedmonston/graphql-authentication/releases/tag/1.7.0) which has these added. Thanks!
