### ISSUE TITLE
Question - Multiple JWT refresh tokens at login

### ISSUE THREAD

**Issue by bartroelands** [jamesedmonston/graphql-authentication#44]
Hi James,

We are doing some tests using your plugin to authenticate users through a mobile app accessing a Craft custom plugin's data. We got the authentication working through Apollo Graphql. One thing we noticed is that every time we authenticate a user in a test call, a new JWT refresh token is created. Is this intended behaviour ? Assuming for every new device a key record is created, but now the effect is that multiple JWT tokens exists supporting the same session. Do we need to keep track of authentication status on the mobile app to deal with this?

**Comment by jamesedmonston** [comment]
@bartroelands Yes, this is intended behaviour. Refresh tokens are consumed when calling the `refreshToken` mutation, so each session/device needs its own token.

An example of this would be if your user logged into the same account across 2 devices. If refresh tokens were shared, once either of the devices called the `refreshToken` mutation, the token would be consumed and the other device would no longer be able to refresh its JWT.

> Do we need to keep track of authentication status on the mobile app to deal with this?

You'll need to keep track of when your JWTs expire, and grab a new one through the `refreshToken` mutation.

See:
- https://lucasmcgartland.medium.com/refreshing-token-based-authentication-with-apollo-client-2-0-7d45c20dc703
- https://github.com/newsiberian/apollo-link-token-refresh
