### ISSUE TITLE
mutation Authenticate - strange  unix date returned.

### ISSUE THREAD

**Issue by GMConsultant** [jamesedmonston/graphql-authentication#45]
I'm testing the authenticate mutation:
There is a problem with the result:
"data": {
        "authenticate": {
"jwtExpiresAt": 1616412117000,
"refreshTokenExpiresAt": 1624355517000,
 }

000 is added to the end, making the unix data incorrect

But if you decode the JWT it's ok!

This is my environment:

Craft CMS 3.6.10
GraphQL Authentication: 1.7.0

PHP version: 7.3.20

**Comment by jamesedmonston** [comment]
@GMConsultant This was done purposely, so that when comparing the expired data in JavaScript using `(new Date()).getTime()` the number of digits matches.
