### ISSUE TITLE
Support for custom elements

### ISSUE THREAD

**Issue by bartroelands** [jamesedmonston/graphql-authentication#46]
Hi James,

Continuing to evaluate the plugin, I was wondering if an how the plugin supports custom elements in managing access. Browsing through you code I see support for entries and assets. I have my own plugin where I use custom elements that I want to manage (read/write only by author) through the plugin.... Haven't tested it fully yes, hence the question if and how this could work

**Comment by bartroelands** [comment]
Hi James,

Seem the plugin can only handle Entries and Assets .. The authorisation and registration works fine. The issue is validating my custom elements. I expose them via the standard token en Bearer of craftCMS. This works fine but we don't have the link with the user voor validation and we need to switch Authorization headers depending on what call we make ... Plus we don't have the individual user based validation .. Any suggestions how to make this work ?

**Comment by jamesedmonston** [comment]
@bartroelands with the Craft team looking to integrate Graph authentication soon (likely Craft 5), I no longer think it'll be worth the investment of time integrating it into the plugin. I'd very happily review and merge a PR if it's something you'd like to see added.

Thanks!
