### ISSUE TITLE
Passing an malformed JWT token throws an error

### ISSUE THREAD

**Issue by Tam** [jamesedmonston/graphql-authentication#47]
When passing an malformed JWT token, this error is thrown:

```
Argument 1 passed to GraphQL\\Type\\Definition\\Type::getNullableType() must be an instance of GraphQL\\Type\\Definition\\Type, null given, called in /var/www/html/vendor/webonyx/graphql-php/src/Validator/Rules/ValuesOfCorrectType.php on line 75
```

**Comment by Tam** [comment]
@jamesedmonston I'm also getting it if I don't pass the auth header at all...

**Comment by jamesedmonston** [comment]
@Tam would you be able to try https://github.com/jamesedmonston/graphql-authentication/commit/b7cbeae2fad0938cb3aeb2e5a389fea3b9956229 and see if it fixes the issue for you?

**Comment by Tam** [comment]
@jamesedmonston Partially, I've made a pull request to fix some other issues

**Comment by jamesedmonston** [comment]
@Tam cool, I'll take a look at the PR this evening. Cheers

**Comment by jamesedmonston** [comment]
@Tam I've merged your PR. Will roll into a release soon. Cheers

**Comment by jamesedmonston** [comment]
@Tam I finally got around to rolling this into a release: https://github.com/jamesedmonston/graphql-authentication/releases/tag/1.8.0
