### ISSUE TITLE
Update the doc

### ISSUE THREAD

**Issue by GMConsultant** [jamesedmonston/graphql-authentication#57]
Hi James!
please update the doc :) 
https://graphql-authentication.jamesedmonston.co.uk/usage/authentication#log-out

**Comment by jamesedmonston** [comment]
Yep! It’s on my list

**Comment by jamesedmonston** [comment]
@GMConsultant done! https://graphql-authentication.jamesedmonston.co.uk/usage/authentication#delete-refresh-tokens
