### ISSUE TITLE
Invalid Authorization Header with "Authorization": "JWT ... " set

### ISSUE THREAD

**Issue by Stalex89** [jamesedmonston/graphql-authentication#58]
I have an issue with the requests where JWT Auth header is required.

It fails with "Invalid Authorization Header" or "Failed to fetch".

Can you please give a hint what can be a cause of an issue ? Thank you

Screenshots from Postman:

Login

<img width="1310" alt="Screenshot 2021-05-18 at 11 13 39" src="https://user-images.githubusercontent.com/23526237/118626426-29a73480-b7cb-11eb-92d7-3707cca63950.png">

Delete tokens

<img width="1299" alt="Screenshot 2021-05-18 at 11 13 21" src="https://user-images.githubusercontent.com/23526237/118626545-417eb880-b7cb-11eb-8a59-cc7526c9059c.png">

Screenshots from the https://graphiql-online.com/graphiql website:

<img width="1678" alt="Screenshot 2021-05-18 at 11 15 33" src="https://user-images.githubusercontent.com/23526237/118626636-56f3e280-b7cb-11eb-9344-317b9103a8d0.png">

<img width="1680" alt="Screenshot 2021-05-18 at 11 18 20" src="https://user-images.githubusercontent.com/23526237/118626736-6c690c80-b7cb-11eb-96d8-7ac83f1c3f4a.png">

**Comment by Zsavajji** [comment]
Hello @jamesedmonston, i experience this problem as well: I can successfully register users, **authenticate** gives back a JWT token, but i cannot query viewer at all.

Did you ever find the root cause of this issue?

**Comment by jamesedmonston** [comment]
@Stalex89 @Zsavajji it would be great to know a little bit more about your setups. Are you using `nginx` or `Apache`? If you're using `Apache`, have you modified your `.htaccess` file to ensure the authorization header is being passed through? https://craftcms.com/docs/3.x/graphql.html#querying-a-private-schema

**Comment by Zsavajji** [comment]
Hi, yes, i came to the same conclusion, it's a matter of Apache's configuration.
I set the CGIPassAuth option and it's now working correctly.
I always worked with NGINX servers so it did seem a bit strange to me that the WS was blocking the header.

Thank you! :)

**Comment by jamesedmonston** [comment]
I've just added a note about this to the docs, to hopefully stop people running into this issue again: https://graphql-authentication.jamesedmonston.co.uk/usage/signing-requests
