### ISSUE TITLE
Support for Google Sign-In

### ISSUE THREAD

**Issue by daltonrooney** [jamesedmonston/graphql-authentication#6]
I saw this mentioned in https://github.com/jamesedmonston/graphql-authentication/issues/3 and wanted to call it out as a potential feature since it's something I could use in a current project. Hopefully this can get on the roadmap and maybe I can even sponsor the feature as @timkelty is helping us with the JWT integration as well.

**Comment by jamesedmonston** [comment]
@daltonrooney yep, definitely something I'm keen on getting added. It's something that I'll likely need on some work project – both upcoming and existing.

I'll try and spend some time looking into it this week 👍🏻

**Comment by jamesedmonston** [comment]
@daltonrooney which services would you like to see integrated?

I'm thinking first round could be:

- Google
- Facebook
- Twitter
- GitHub
- Apple

**Comment by jamesedmonston** [comment]
@daltonrooney I've just created a project in which I'll track the progress: https://github.com/jamesedmonston/graphql-authentication/projects/1

**Comment by daltonrooney** [comment]
That's so awesome that you're already making progress on this. 👍 

Google would be my top choice - we're working with a school on a Craft build right now, and they use Google as their email provider. One of the things that would be important to them is to limit logins to a particular domain. Before this project went headless, we were considering the Social plugin, [which includes that capability](https://docs.dukt.net/social/v2/configuration.html#lockdomains).

Even if that ends up not being an appropriate feature for this plugin, some kind of event we hook into during the process would be great.

**Comment by jamesedmonston** [comment]
@daltonrooney Making some progress on the Google Sign-In stuff!

<img width="1792" alt="Screenshot 2020-11-24 at 11 50 39" src="https://user-images.githubusercontent.com/4851924/100090588-4893c200-2e4b-11eb-8154-d22a230d2373.png">

**Comment by jamesedmonston** [comment]
@daltonrooney I've updated the title for this issue to relate specifically to Google Sign-In. I will create separate cards for the separate services, so they can each be assigned to different projects as I work through them.

**Comment by jamesedmonston** [comment]
@daltonrooney Sorry for yet another ping, but if you run the latest commit from the `develop` branch, you should be able to start playing around with the Google Sign-In mutation. Note: the mutation will only appear once you've filled in your Client ID in settings:

<img width="1792" alt="Screenshot 2020-11-24 at 17 06 08" src="https://user-images.githubusercontent.com/4851924/100127940-86a6db00-2e77-11eb-8687-304fcaff33ab.png">

**Comment by daltonrooney** [comment]
@jamesedmonston Is there any way to hook into the signIn mutation response? I'd like to return a list of the user's groups to help with client-side routing.

**Comment by jamesedmonston** [comment]
@daltonrooney I've just added a `schema` field to the responses in `authenticate`, `register` and `googleSignIn` (along with the user group specific mutations).

Can you try updating to https://github.com/jamesedmonston/graphql-authentication/commit/d27daa8362f5848aa4a2e91c316cd462d477e35b and check if it's working okay for you?

Cheers
