### ISSUE TITLE
Request Cookie Not Being Set

### ISSUE THREAD

**Issue by jstevens79** [jamesedmonston/graphql-authentication#62]
I'm trying to get the HttpOnly cookies to set properly in the browser. I can see that the Authenticate request returns a response cookie, but it doesn't set it in the browser. I have the settings set to Lax in the Craft plugin, and then on client side, I'm using graphql-request with the following settings. Any ideas what's going wrong and why the cookie isn't setting properly?

`import fetch from 'cross-fetch';

const client = new GraphQLClient("[my-site]/api", {
  headers: {
    Authorization: "Bearer ...[bearer token]",
  },
  credentials: 'include',
  fetch
});`

**Comment by jamesedmonston** [comment]
@jstevens79 how are your back-end and front-end domains set up? Are they currently on separate origins? I've not had much luck getting them to send across domains (even with `lax` set) as browsers seem to block them as tracking cookies. Which browser are you testing on out of interest?
