### ISSUE TITLE
updateViewer mutation throws error.

### ISSUE THREAD

**Issue by keshavsharma** [jamesedmonston/graphql-authentication#70]
I am using this mutation for saving custom user fields, after user registration. But it throws error given below:

[error][PDOException] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`craft_dev`.`dfd_relations`, CONSTRAINT `dfd_fk_omntsbauduofwbpoxdeoldsfurvgnfjdwqoq` FOREIGN KEY (`targetId`) REFERENCES `dfd_elements` (`id`) ON DELETE CASCADE) in /var/www/craft-dev/vendor/yiisoft/yii2/db/Command.php:1302

**Comment by jamesedmonston** [comment]
Are you able to supply any more information? It would be good to see the mutation you’re trying, and to know the types of fields you’re trying to update.

**Comment by keshavsharma** [comment]
I have generated query to update User Custom fields: of type ( String, Matrix, Checkboxes, User, Address field ( part of https://plugins.doublesecretagency.com/) ) , Address field is not used in query yet. I have tried removing matrix fields also from mutation query, But it didn't work.

Here is query: 
mutation UpdateUser($checkForOpenPositions: [String], $checkForSwapPositions: [String], $partnersResidentswapIdNumber: [Int], $receiveEmailAlerts: [String], $receiveTextAlertsSentToMyMobilePhone: [String], $telephoneNumber: String, $togetherAnywhereMode: [String], $locationFilterBlocks: [locationFilter_MatrixBlockContainerInput], $specialtyFilterBlocks: [specialtyFilter_MatrixBlockContainerInput], $specialtyFilterSortOrder: [QueryArgument], $locationFilterSortOrder: [QueryArgument]) {
  updateViewer(
    checkForOpenPositions: $checkForOpenPositions
    checkForSwapPositions: $checkForSwapPositions
    partnersResidentswapIdNumber: $partnersResidentswapIdNumber
    receiveEmailAlerts: $receiveEmailAlerts
    receiveTextAlertsSentToMyMobilePhone: $receiveTextAlertsSentToMyMobilePhone
    telephoneNumber: $telephoneNumber
    togetherAnywhereMode: $togetherAnywhereMode
    locationFilter: {sortOrder: $locationFilterSortOrder, blocks: $locationFilterBlocks}
    specialtyFilter: {sortOrder: $specialtyFilterSortOrder, blocks: $specialtyFilterBlocks}
  ) {
    id
    __typename
  }
}

 
{
	"variables": {
		"checkForOpenPositions": [
			"1"
		],
		"checkForSwapPositions": [],
		"locationFilterBlocks": [],
		"partnersResidentswapIdNumber": [
			2
		],
		"receiveEmailAlerts": [
			"1"
		],
		"receiveTextAlertsSentToMyMobilePhone": [
			"1"
		],
		"specialtyFilterBlocks": [
			{
				"specialty": {
					"pgy": 75,
					"specialty": 18
				}
			},
			{
				"specialty": {
					"pgy": 78,
					"specialty": 105
				}
			}
		],
		"telephoneNumber": "3423",
		"togetherAnywhereMode": [
			"1"
		]
	}
}

![image](https://user-images.githubusercontent.com/10434971/132869073-6f13beaa-2168-4f4c-bedf-a0175b3dc4f8.png)
![image](https://user-images.githubusercontent.com/10434971/132869154-ff2ebccc-8de1-4ad9-a821-25e813a961cd.png)
![image](https://user-images.githubusercontent.com/10434971/132869291-0aefb515-a141-4728-8a5d-73ff82ac9b55.png)

**Comment by keshavsharma** [comment]
I found this issue is related to Craft CMS core, It happens when we try to assign non existing user id, to "Users" type field in Query parameters.
Craft CMS should send exception message like below, instead of failed sql errors. 

I'm using Angular frontend with graphql.

My query seems working now, but it still not seems updating Matrix fields.

I found this another problem in query below. It works well after login, But If user's JWT get expired and we execute query by using authorization header:
query: query QrySpecialty {
  entries(section: "specialties", orderBy: "title") {
    title
    id
    __typename
  }
}

It returns 

{
	"errors": [
		{
			"message": "Something went wrong when processing the GraphQL query."
		}
	]
}


There should be some error code in message, So that we can handle redirect to login page, if token get expired.  Please update me if there is any such feature exist in this plugin.

**Comment by jamesedmonston** [comment]
@keshavsharma  I've just pushed version `1.11.5` which improves the way errors are handled in production environments. You'll now see `Invalid Authorization Header` on requests with an expired/invalid token.

**Comment by keshavsharma** [comment]
Thanks for update, i will update it soon.
Thanks & Regards
Keshav Sharma 

    On Monday, 27 September, 2021, 07:16:41 pm IST, James Edmonston ***@***.***> wrote:  
 
 


@keshavsharma I've just pushed version 1.11.5 which improves the way errors are handled in production environments. You'll now see Invalid Authorization Header on requests with an expired/invalid token.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
