### ISSUE TITLE
Social login activation URL

### ISSUE THREAD

**Issue by magicspon** [jamesedmonston/graphql-authentication#72]
Hello,

If validate email is set to true, and a user registers/logs in via google (apple, twitter etc), the activation email sent is the "set-password" one.

Ideally it would send them the regular activation email.

Is there anyway I can make it so?

Thanks
Dave

**Comment by jamesedmonston** [comment]
@magicspon sounds like a bug, I'll take a look. Cheers

**Comment by jamesedmonston** [comment]
@magicspon released in 2.0 (finally)!
