### ISSUE TITLE
Can't buy and install - This plugin requires PHP ^7.4 || ^8.0, but your composer.json file is currently set to 7.4.26.

### ISSUE THREAD

**Issue by Fragilem17** [jamesedmonston/graphql-authentication#82]
Hi There,

I'm facing an issue with purchasing the plugin.
The box is disabled in Craft and the message is saying my php version is wrong.
however.. composer has been updated to a version that is above 7.4.0

[edit: managed to manually do the composer install and that seems to have worked, but the box still looks disabled]

Any ideas?
Best regards,
Tom

**Comment by jamesedmonston** [comment]
Would you be able to post your `composer.json` contents here, please?

Also, what PHP version shows when going to `Utilities -> System Report`?

**Comment by Fragilem17** [comment]
`{
  "require": {
    "craftcms/cms": "^3.6.4",
    "craftcms/feed-me": "4.4.0",
    "jamesedmonston/graphql-authentication": "^1.12",
    "vlucas/phpdotenv": "^3.4.0"
  },
  "require-dev": {
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.4.26"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}
`

Utilities -> System Report   = PHP version | 7.4.26

**Comment by jamesedmonston** [comment]
Does it work if you change the `php` value to `"7.4"` in `composer.json`?

**Comment by Fragilem17** [comment]
Changed it, but it's hard to test right now as its already bought and installed, so the "buy box" shows as disabled anyway and the requirement message is gone.

**Comment by jamesedmonston** [comment]
Ah, that makes sense. It feels like it's more of a Composer issue, but it could be something to do with my setup. I'll do some testing.

(Thanks for buying!)
