### ISSUE TITLE
Viewer query returns info without viewer being activated (because registration already provides a jwt)

### ISSUE THREAD

**Issue by Fragilem17** [jamesedmonston/graphql-authentication#83]
Hi,

I'm wondering if this is by design?

When you register (mutation Register) a JWT token is sent over by the registration process. 
Using that JWT you can do just about anything that is in that schema.
**(That seems weird to me as the user is not activated yet)**

Login at this time does not return a JWT token which I think is correct.
(It correctly returns the string "Please activate your account before logging in")

When I query the viewer (using the registration token) I get all viewer information even though the user is not activated yet.
Maybe this is by design but it seems weird to me. (in my case, i don't want that even though it probably is only the info linked to that user)

When the user activates (mutation ActivateUser) no JWT token is sent.
Maybe this could be the first time to actually send it over, then the user is authenticated the moment they click the activation link. (edit: on second, not sending a JWT is probably better.. as the activation email would then give access to the user even though at no point in time the email and password has to be typed in on that client)

Maybe I should open another "Issue" but i'm also not understanding the "fields" tab. I've set everything there to "private" but can still query channels connected to my user. (through query Viewer). I see no need for this tab as you can already set these privileges in the default Craft GraphQL Schemas right?

Would it make sense to be able to set a Schema for people who register (they would receive a JWT token upon registering with access to that schema alone) and a different (or the same) Schema for people who subsequently activate their account expanding their permissions in the process. a change to the codebase like this would be backwards compatible (by default you set the same schema before and after activation)

[Edit: typos and clarification]
[Edit: more clarifications and a suggestion that would fix my issue]

**Comment by jamesedmonston** [comment]
@Fragilem17 I'll likely release this update as part of the `2.0` migration to Craft 4. It'll be a breaking change for most people, so don't want to release as a patch for `1.x`.

**Comment by jamesedmonston** [comment]
@Fragilem17 hey, I've just pushed a commit for this. All requests using the JWT returned from the `register` mutation now throw a `Please activate your account` error, until the account has been activated.

**Comment by jamesedmonston** [comment]
@Fragilem17 released in 2.0!

**Comment by james-em** [comment]
@jamesedmonston 

We are currently updating a CraftCMS 3.x to 4.x and we upgraded your plugin as well. Is there a way to restore the previous behavior? The app has multiple step for the registration processed and we're now getting "Please activate your account before logging in" in one of the steps.

Thanks in adavance!

**Comment by jamesedmonston** [comment]
@james-em I've added a new setting for skipping the activation status on requests.

<img width="700" alt="Screenshot 2023-03-04 at 10 37 30" src="https://user-images.githubusercontent.com/4851924/222895319-61e5e4c0-a9e5-4231-b622-2181f596cae6.png">

**Comment by jamesedmonston** [comment]
@james-em that's released in `2.4.0` FYI!

**Comment by james-em** [comment]
> @james-em that's released in `2.4.0` FYI!

Yes thank you !! Very appreciated ! Way better than patching the CraftCMS 4.x column 'active' to always be true in DB
