### ISSUE TITLE
feature request - Ability to delete your user account.

### ISSUE THREAD

**Issue by Fragilem17** [jamesedmonston/graphql-authentication#84]
Would be great if, next to being able to update your password and personal data, you could also delete your account using GraphQL.
This would make it a bit more compliant with GDPR

Thanks for making this plugin! it's working great so far!

Tom

**Comment by jamesedmonston** [comment]
@Fragilem17 Great idea.

Initially I can see two ways of implementing this, do you have any thoughts?

- A mutation where you supply (and confirm) password, which instantly deletes the user
- A mutation that fires off an email with a confirmation link/code, which you then pass into an additional mutation that does the deletion

**Comment by Fragilem17** [comment]
Hi James, 

I think the first one would be the most developer friendly ;-)
So you provide the JWT (have to be logged in first) and the password to the delete mutation and it's done.
Feels save enough i think.

T

**Comment by rjgux** [comment]
One way we have approached this is to use a graphql mutation to set a 'Cancel Account' lightswitch field to field to true. We then have a task that checks user accounts that match the criteria and deletes them on a schedule.

**Comment by jamesedmonston** [comment]
@Fragilem17 released in 2.0!
