### ISSUE TITLE
Twig error introduced with Craft 3.7.24

### ISSUE THREAD

**Issue by daveyjones** [jamesedmonston/graphql-authentication#85]
I'm getting the following error when trying to load the settings page:

`Argument 1 passed to craft\web\twig\variables\Cp::field() must be of the type string, null given, called in /var/www/staging/vendor/twig/twig/src/Extension/CoreExtension.php on line 1511`

I believe this started as soon as I upgraded to [Craft 3.7.24](https://github.com/craftcms/cms/blob/main/CHANGELOG.md#3724---2021-12-02).

<img width="1280" alt="Screen Shot 2021-12-02 at 10 21 44 PM" src="https://user-images.githubusercontent.com/2852617/144555740-aa480555-ea1d-4b51-9fbe-1968603482a6.png">

**Comment by jamesedmonston** [comment]
I'm able to reproduce this locally. Looking into it now.

**Comment by daveyjones** [comment]
Thanks! Do you know when an update will be available? I tried applying these changes manually but I'm still getting an error...I may have missed something.

**Comment by daveyjones** [comment]
Awesome, thanks! I just replaced the plugin directory with the `develop` branch from GitHub for now (until an update is available). Everything is working great now.

**Comment by jamesedmonston** [comment]
@daveyjones 1.12.2 is out now with this fix, thanks!
