### ISSUE TITLE
Cannot remove from my plugins

### ISSUE THREAD

**Issue by uhohbananatime** [jamesedmonston/graphql-authentication#87]
I cannot seem to remove the plugin, I have tried removing the auth key, then uninstalling, then removing it, and some how it always comes back as "Missing".

How do I remove this entirely?

<img width="1176" alt="shot" src="https://user-images.githubusercontent.com/62956235/146174909-f0fbf985-bd66-422e-b219-8fb0672ca599.png">

**Comment by magicspon** [comment]
I've seen this issue with some other plugins... i think this is a craft issue more than a `graphql-authentication` issue

**Comment by uhohbananatime** [comment]
I agree with you there, noticed it has the same impact on another plugin, thanks for giving it a look!
