### ISSUE TITLE
Invalid Refresh Token: What's the correct approach?

### ISSUE THREAD

**Issue by palomamtnez** [jamesedmonston/graphql-authentication#88]
First of all, thanks for an amazing plugin, it has made my life easier :)

I just have a question, when is it expected to refresh the JWT and refreshToken ?

E.g. in my app, as soon as the user logs in, the tokens are stored successfully.
Then, in every request that the user makes in the frontend, it carries the JWT in the authorization headers and works fine.
But eventually, this token expires, and now the user gets "Invalid Authorization Header", which makes sense at this point.
Then I thought that the correct way to do this was to listen to the error code type, and if it is the **authentication** error type, then  **refresh the token** using this mutation to get a new token and store it again and then let the user continue with the request that had failed:

```
mutation RefreshToken {
  refreshToken(refreshToken: "Bc7xqt6ri5vFEzIEXRo-Z0CxgG0RqF_L") {
    jwt
    jwtExpiresAt
    refreshToken
    refreshTokenExpiresAt
  }
}
```

but by the time I request this new token, the provided token has already expired, so it returns me this error

```
{
  "errors": [
    {
      "message": "Invalid Refresh Token",
      "extensions": {
        "code": "INVALID",
        "category": "graphql"
      }
    }
  ]
}
```

So, which is the flow that is proposed to renew the refreshToken? 

Thanks!

**Comment by jamesedmonston** [comment]
Hey, thanks for the kind words!

At a high level it sounds like you're doing everything correctly 🤔, would you be able to share the token expiry section of your plugin settings? Is your refresh token expiry set to a longer expiry than the JWT expiry?

Thanks!

**Comment by jpcarpenter** [comment]
Also hitting this. I have the refreshToken expiration set to 1 Week, the JWT expiration set to 30 min, and the SameSite Cookie Policy set to "None".

Here is how I'm sending the RefreshToken mutation:

```javascript
const currentRefreshToken = getCookie(event, "refreshToken");

const refreshResponse = (await $fetch(apiUrl, {
  method: "POST",
  headers: {
    "content-type": "application/json",
    "authorization": `Bearer ${gqlToken}`, // my GQL endpoint requires a token
  },
  body: JSON.stringify({
    query: `mutation RefreshToken {
      refreshToken(refreshToken: "${currentRefreshToken}") {
        jwt
        jwtExpiresAt
        refreshToken
        refreshTokenExpiresAt
      }
    }`,
  }),
}));

console.log(refreshResponse); // returns: { errors: [ { message: 'Invalid Refresh Token', extensions: [Object] } ] }
```

FWIW, below is how I'm setting the cookies once someone logs in successfully:

```javascript

// Utility function to set JWT cookies
export const setJWTCookies = (
  event: H3Event, 
  jwt: string, 
  refreshToken: string, 
  jwtExpiresAt: number, 
  refreshTokenExpiresAt: number
) => {

  // Set the JWT
  setCookie(event, "authToken", jwt, {
    httpOnly: true,
    path: "/",
    expires: new Date(Date.now() + jwtExpiresAt * 1000),
  });

  // Set the refreshToken
  setCookie(event, "refreshToken", refreshToken, {
    httpOnly: true,
    path: "/",
    expires: new Date(Date.now() + refreshTokenExpiresAt * 1000),
  });
};

```
