### ISSUE TITLE
Question: Does this take care of all requirement for CSRF protection in my login and sign up forms? 

### ISSUE THREAD

**Issue by toddpadwick** [jamesedmonston/graphql-authentication#91]
I'm new to handling security protocols and authorising users on a headless set-up. Only done that with twig before on classic craft sites. 
With this plugin, do I still need to find a solution for handling CSRF tokens? Or does JWT auth make CSRF protection redundant?

If I do need further CSRF protection on my forms, do you have any advice for this?

FYI, I am using Nuxt.js and Apollo.

**Comment by jamesedmonston** [comment]
@toddpadwick setting your [`allowedGraphqlOrigins`](https://craftcms.com/docs/3.x/config/config-settings.html#allowedgraphqlorigins) value in `general.php` to the your front-end URL should be all you need to do.

Another security tip would be to disable the introspection query in production using the [`enableGraphqlIntrospection`](https://craftcms.com/docs/3.x/config/config-settings.html#enablegraphqlintrospection) setting.
