### ISSUE TITLE
Reduce dependency install size

### ISSUE THREAD

**Issue by Tam** [jamesedmonston/graphql-authentication#92]
this plz my composer just timed-out because google https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services

**Comment by Tam** [comment]
bump

**Comment by Tam** [comment]
+1

**Comment by jamesedmonston** [comment]
@Tam looks like this has to be added to your project's `composer.json` file. I tried adding it into the plugin's one, but it doesn't seem to work.

If you're running composer inside Docker, I'd recommend installing it through `brew` and running it globally – it's _so_ much faster on my machine.

**Comment by jamesedmonston** [comment]
@Tam I'll add a note to the docs for this. It _does_ reduce the size by about 46MB...

It won't help the install time, though, as it cleans up _after_ install but _before_ autoloading.
