### ISSUE TITLE
Authenticated users see only their own entries.

### ISSUE THREAD

**Issue by GMConsultant** [jamesedmonston/graphql-authentication#96]
The problem is just for the display everything else works perfectly.
In the USERS configuration I have **not** set any query / mutation limit for the user: 

**Restricted Entry Queries**: not checked
**Restricted Entry Mutations**: not checked
**Restricted Asset Queries**:  not checked
**Restricted Asset Mutations**: not checked

In the FILEDS configuration are all to defalut (Query & Mutuate)

If the user is connected via JWT, all others entries disapperas..
if user logout all entries are visible.

_i think the above fields are not passed as per config ..._

**PHP v 8.1.8**
**Craft CMS 3.7.46**

**Comment by GMConsultant** [comment]
@jamesedmonston  can you help me? 
or the plugin has been abandoned?

**Comment by jamesedmonston** [comment]
@GMConsultant see the docs: https://graphql-authentication.jamesedmonston.co.uk/extra/fyi#entry-and-asset-queries
